// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7kT3Lm0e_zG6dnlhEYfpxsHk0iAuTpTE',
    appId: '1:130946680957:android:d8e18de20f1f76822b0914',
    messagingSenderId: '130946680957',
    projectId: 'taski-5e760',
    storageBucket: 'taski-5e760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWUBzOctntIOsCa6o1WkOk3cjZM5rRRrc',
    appId: '1:130946680957:ios:e98b8b3b8e53a7112b0914',
    messagingSenderId: '130946680957',
    projectId: 'taski-5e760',
    storageBucket: 'taski-5e760.firebasestorage.app',
    androidClientId: '130946680957-fvkathqags3edmat9ia5umbqa4ld376r.apps.googleusercontent.com',
    iosClientId: '130946680957-m756ro44vo3vkom70dqrd10jvk3cieg7.apps.googleusercontent.com',
    iosBundleId: 'com.taski.taski',
  );

}